// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: lnk.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LinksClient is the client API for Links service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinksClient interface {
	// Get a list of all the shortened links as well as metadata about their usage.
	ListLinks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LinkList, error)
	// Create a new shortened link that when visited, it will redirect to the target url.
	CreateLink(ctx context.Context, in *CreateLinkReq, opts ...grpc.CallOption) (*LinkId, error)
	// Obtain details for a shortened link, like how many times it was visited and its daily
	// visits breakdown.
	GetLink(ctx context.Context, in *LinkId, opts ...grpc.CallOption) (*LinkDetails, error)
	// Delete the specified shortened link as well including its metadata.
	DeleteLink(ctx context.Context, in *LinkId, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type linksClient struct {
	cc grpc.ClientConnInterface
}

func NewLinksClient(cc grpc.ClientConnInterface) LinksClient {
	return &linksClient{cc}
}

func (c *linksClient) ListLinks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LinkList, error) {
	out := new(LinkList)
	err := c.cc.Invoke(ctx, "/lnk.Links/ListLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) CreateLink(ctx context.Context, in *CreateLinkReq, opts ...grpc.CallOption) (*LinkId, error) {
	out := new(LinkId)
	err := c.cc.Invoke(ctx, "/lnk.Links/CreateLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) GetLink(ctx context.Context, in *LinkId, opts ...grpc.CallOption) (*LinkDetails, error) {
	out := new(LinkDetails)
	err := c.cc.Invoke(ctx, "/lnk.Links/GetLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linksClient) DeleteLink(ctx context.Context, in *LinkId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/lnk.Links/DeleteLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinksServer is the server API for Links service.
// All implementations must embed UnimplementedLinksServer
// for forward compatibility
type LinksServer interface {
	// Get a list of all the shortened links as well as metadata about their usage.
	ListLinks(context.Context, *emptypb.Empty) (*LinkList, error)
	// Create a new shortened link that when visited, it will redirect to the target url.
	CreateLink(context.Context, *CreateLinkReq) (*LinkId, error)
	// Obtain details for a shortened link, like how many times it was visited and its daily
	// visits breakdown.
	GetLink(context.Context, *LinkId) (*LinkDetails, error)
	// Delete the specified shortened link as well including its metadata.
	DeleteLink(context.Context, *LinkId) (*emptypb.Empty, error)
	mustEmbedUnimplementedLinksServer()
}

// UnimplementedLinksServer must be embedded to have forward compatible implementations.
type UnimplementedLinksServer struct {
}

func (UnimplementedLinksServer) ListLinks(context.Context, *emptypb.Empty) (*LinkList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLinks not implemented")
}
func (UnimplementedLinksServer) CreateLink(context.Context, *CreateLinkReq) (*LinkId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLink not implemented")
}
func (UnimplementedLinksServer) GetLink(context.Context, *LinkId) (*LinkDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLink not implemented")
}
func (UnimplementedLinksServer) DeleteLink(context.Context, *LinkId) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLink not implemented")
}
func (UnimplementedLinksServer) mustEmbedUnimplementedLinksServer() {}

// UnsafeLinksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinksServer will
// result in compilation errors.
type UnsafeLinksServer interface {
	mustEmbedUnimplementedLinksServer()
}

func RegisterLinksServer(s grpc.ServiceRegistrar, srv LinksServer) {
	s.RegisterService(&Links_ServiceDesc, srv)
}

func _Links_ListLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).ListLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnk.Links/ListLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).ListLinks(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_CreateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLinkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).CreateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnk.Links/CreateLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).CreateLink(ctx, req.(*CreateLinkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_GetLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).GetLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnk.Links/GetLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).GetLink(ctx, req.(*LinkId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Links_DeleteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinksServer).DeleteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnk.Links/DeleteLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinksServer).DeleteLink(ctx, req.(*LinkId))
	}
	return interceptor(ctx, in, info, handler)
}

// Links_ServiceDesc is the grpc.ServiceDesc for Links service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Links_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lnk.Links",
	HandlerType: (*LinksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLinks",
			Handler:    _Links_ListLinks_Handler,
		},
		{
			MethodName: "CreateLink",
			Handler:    _Links_CreateLink_Handler,
		},
		{
			MethodName: "GetLink",
			Handler:    _Links_GetLink_Handler,
		},
		{
			MethodName: "DeleteLink",
			Handler:    _Links_DeleteLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lnk.proto",
}
