// Package api provides the models returned by the api as well as the
// different request and response structs needed for interacting with it.
//
// There is also an openapi schema definition that, while not autogenerated
// at the moment, it should cover all the api.
package api
